package com.terrasage.api.encyclopedia.dto

import com.terrasage.api.encyclopedia.entity.*

data class SpeciesDetailResponse(
    val id: Long,
    val scientificName: String,
    val commonNameKo: String,
    val commonNameEn: String?,
    val kingdom: String,
    val phylum: String,
    val taxonomyClass: String,
    val taxonomyOrder: String,
    val family: String,
    val genus: String,
    val origin: String?,
    val habitat: String?,
    val lifespanCaptive: Int?,
    val lifespanWild: Int?,
    val avgSizeCm: Double?,
    val avgWeightG: Double?,
    val difficultyLevel: DifficultyLevel,
    val category: SpeciesCategory?,
    val citesLevel: CitesLevel?,
    val legalStatusNote: String?,
    val thumbnailUrl: String?,
    val status: SpeciesStatus,
    val animalCareGuide: AnimalCareGuideResponse?,
    val plantCareGuide: PlantCareGuideResponse?,
    val variants: List<VariantResponse>,
) {
    companion object {
        fun from(
            species: Species,
            animalCareGuide: AnimalCareGuide?,
            plantCareGuide: PlantCareGuide?,
            variants: List<Variant>,
        ) = SpeciesDetailResponse(
            id = species.id,
            scientificName = species.scientificName,
            commonNameKo = species.commonNameKo,
            commonNameEn = species.commonNameEn,
            kingdom = species.kingdom,
            phylum = species.phylum,
            taxonomyClass = species.taxonomyClass,
            taxonomyOrder = species.taxonomyOrder,
            family = species.family,
            genus = species.genus,
            origin = species.origin,
            habitat = species.habitat,
            lifespanCaptive = species.lifespanCaptive,
            lifespanWild = species.lifespanWild,
            avgSizeCm = species.avgSizeCm,
            avgWeightG = species.avgWeightG,
            difficultyLevel = species.difficultyLevel,
            category = species.category,
            citesLevel = species.citesLevel,
            legalStatusNote = species.legalStatusNote,
            thumbnailUrl = species.thumbnailUrl,
            status = species.status,
            animalCareGuide = animalCareGuide?.let { AnimalCareGuideResponse.from(it) },
            plantCareGuide = plantCareGuide?.let { PlantCareGuideResponse.from(it) },
            variants = variants.map { VariantResponse.from(it) },
        )
    }
}
